apiVersion: v1
kind: Service
metadata:
  name: Service_NAME
  namespace: NAMESPACE
spec:
  type: LoadBalancer
  selector:
    app: Service_NAME
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
